baseURL = "/"
title = "Lirik"
subtitle = "Lirik lagu inggris terjemahan"
theme = "beautifulhugo"
contentDir = "content"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
    mainSections = ["song","songs"]
    hideAuthor = true
#    since = 2022
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = false
    wordCount = false
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true

[[menu.main]]
    name = "Lagu"
    url = ""
    weight = 1
[[menu.main]]
    name = "Tentang"
    url = "page/tentang"
    weight = 2

    # [languages.en]
    #     languageName = "English"
    #     title = "Lyrics"
    #     subtitle = "English song lyrics translated"
    #     [[languages.en.menu.main]]
    #         name = "Songs"
    #         url = ""
    #         weight = 1
    #     [[languages.en.menu.main]]
    #         name = "About"
    #         url = "page/about"
    #         weight = 2
